AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  envelopeApi
  
  Sample SAM Template for envelopeApi

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 300
    Tracing: Active
    CodeUri: bin/
    Runtime: go1.x
    Environment:
      Variables:
        SECRET: "secret"
        CLIENT: "client"

Resources:

  InitApiFunction:
    Type: AWS::Serverless::Function  
    Properties:
      Handler: initApi
      Events:
        InitApi:
          Type: Api
          Properties:
            Path: /
            Method: GET

  CallbackFunction:
    Type: AWS::Serverless::Function  
    Properties:
      Handler: callback
      Events:
        InitApi:
          Type: Api
          Properties:
            Path: /callbackUrl
            Method: GET
